services:
  # frontend:
  #   image: nginx-three.js
  #   build:
  #     context: ./Front-end
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080"
  #   depends_on:
  #     backend:
  #       condition: service_started
  #     db:
  #       condition: service_started

  # backend:
  #   image: node.js-express
  #   build:
  #     context: ./Back-end
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000"

  db:
    container_name: Lazyfield-DB
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${Lazyfield_DATABASE_PASSWORD}
      POSTGRES_USER: ${Lazyfield_DATABASE_USER}
      POSTGRES_DB: ${Lazyfield_DATABASE_NAME}