CREATE TABLE Users (
  userID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  username VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  carot INT NOT NULL DEFAULT 0,
  isAdmin BOOLEAN NOT NULL
);

CREATE TABLE GameState (
  gameID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  userID UUID NOT NULL,
  clicks INT DEFAULT 0,
  upgrades JSON DEFAULT '{}',
  lastSaved TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE
);